.gitignore
package.json
yarn.lock

Plugin packaging format is changing in Flipper and the previous format is being deprecated: https://fbflipper.com/docs/extending/js-setup#migration-to-the-new-plugin-specification. 
This PR migrates the plugin definition to the new format.

Migration to the Flipper plugin spec v2

---

ios/flipper-plugin-react-native-performance.xcodeproj/project.pbxproj

Couldn't get the autolinker to detect the package without this, even if I place a `react-native.config.js` file. The file isn't used AFAICT, and it's historically only needed for linking without cocoapods which also isn't a thing anymore.

Add mock xcodeproj to support autolinking

---

packages/flipper-plugin-performance/src/Timeline.js
packages/flipper-plugin-performance/src/lib/formatMilliseconds.js

This PR adds tooltips when hovering over individual measures on the timeline. Additionally it centralizes layouting logic to one place that make the code a bit simpler and should also be slightly faster.

Add tooltips to measures on timeline

---

examples/vanilla/android/build.gradle
packages/react-native-performance/android/build.gradle
packages/react-native-performance/android/gradle.properties
packages/react-native-performance/android/src/main/java/com/oblador/performance/PerformanceModule.java

`minSdkVersion` was set to 21, but works just fine with 16 which is the default for RN projects so I changed it so that 16 is default but that it would respect the settings from the root project. Additionally I made it compile with Android Studio, and I think the if statement should make it not break in consumers anymore.

Respect root project gradle settings

---

package.json
packages/flipper-plugin-performance/package.json
packages/react-native-performance-flipper-reporter/package.json
packages/react-native-performance/package.json

This small PR:
* fixes the typo in the `react-native-performance-flipper-reporter` peer dependency (currently used name do not exist in the npm registry), 
* adds `directory` data to the `repository` field in packages `package.json` files (https://docs.npmjs.com/cli/v7/configuring-npm/package-json#repository),
* removes `name` from the main workspace file, which is not necessary in the current repository setup.
It looks like the new release of `react-native-performance-flipper-reporter` will be required to fix the `example` and other projects using that package.

fix flipper-reporter peerDependency, update repository fields

---

examples/vanilla/ios/Podfile.lock
package.json
yarn.lock

Additionally it fixes metro version conflicts with react-native making the plugin build fail on some yarn versions.

Bump flipper-pkg to 76

---

packages/react-native-performance/package.json
packages/react-native-performance/src/performance.ts
packages/react-native-performance/test/user-timing-3.spec.ts
packages/react-native-performance/tsconfig.build.json

Not perfect to have the default values implemented twice, but I also don't want to call `now()` unless necessary.

Fix lack of fallback values for user timing 3 implementation

---

packages/react-native-performance/android/src/main/java/com/oblador/performance/PerformanceModule.java

This will make sure that the timestamps on both native and JavaScript match each other as `performance.now()` does not include time spent in sleep.
> Returns milliseconds since boot, not counting time spent in deep sleep.
source: [uptimeMillis](https://developer.android.com/reference/android/os/SystemClock#uptimeMillis())
> Returns milliseconds since boot, including time spent in sleep.
source: [elapsedRealtime](https://developer.android.com/reference/android/os/SystemClock#elapsedRealtime())

Use uptimeMillis on Android

---

packages/flipper-plugin-performance/README.md

Use the new package name from npm `flipper-plugin-performance`. The name from the readme links to an older version of the plugin `0.6.0` which is outdated by 2 months.

Update the name for flipper plugin

---

packages/react-native-performance/android/src/main/AndroidManifest.xml
packages/react-native-performance/android/src/main/java/com/oblador/performance/PerformanceModule.java
packages/react-native-performance/android/src/main/java/com/oblador/performance/StartTimeProvider.java

Instead of getting process start time from proc stat file, it is getting process cpu elapsed time and subtracting from uptime of static initialised module variable.
I tried existing and new measurement with Android 11 and Android 6 emulator 10 times. Here are the results.(the first number is new and the second number is existing measurement.)
Vanilla: 
Android M:  (63 - 66), (46 - 48), (67 - 64), (51-50), (63-65), (60-56), (51-68), (26-42), (40-52), (29-38) 
Android 11: (98 - 190), (111 - 218), (120 - 188), (116 - 222), (96 - 173), (100 - 176), (97 - 204), (85 - 175), (194 - 260), (98 - 189) 
RNN:
Android M:  (56 - 59), (79-84), (43 - 71). (77 - 87). (59 - 74), (91 - 91), (49-69), (48-79), (59-60), (44-62)
Android 11: (422 - 610), (246 - 310), (403 - 578), (262 - 334), (246 - 347), (272 - …

android native start time fix

---

packages/react-native-performance/android/src/main/java/com/oblador/performance/PerformanceModule.java
packages/react-native-performance/android/src/main/java/com/oblador/performance/StartTimeProvider.java
packages/react-native-performance/ios/RNPerformanceManager.m
packages/react-native-performance/ios/react-native-performance.podspec

In React Native 0.68 the `Performance.now()` implementation on both iOS and Android changed to use unix epoch timestamps instead of a monotonic clock in https://github.com/facebook/react-native/pull/32695. 
This is clearly inferior for the purposes of performance metrics as it risks skewing durations, but it's more important to keep the native marks in sync with the RN implementation which this PR aims to do. This means this is a breaking change only compatible with RN >=0.68.

Use unix epoch timestamps

---

examples/react-native-navigation/ios/Podfile.lock
examples/vanilla/App.tsx
examples/vanilla/android/gradle.properties
examples/vanilla/ios/Podfile
examples/vanilla/ios/Podfile.lock
packages/react-native-performance/android/build.gradle
packages/react-native-performance/android/src/main/java/com/oblador/performance/PerformanceModule.java
packages/react-native-performance/ios/RNPerformanceManager.mm
packages/react-native-performance/ios/react-native-performance.podspec
packages/react-native-performance/package.json
packages/react-native-performance/src/NativeRNPerformanceManager.js
packages/react-native-performance/src/index.ts

In preparation of the rollout of the new architecture in React Native this PR adds support for TurboModules while keeping backwards support. To ease integration for old architecture users the Android implementation is not using codegen, _but_ since the module on Android is basically only an event emitter there is quite limited value in even having it (iOS on the other hand actually has methods).

Support TurboModules

---

packages/react-native-performance/README.md

With https://github.com/oblador/react-native-performance/pull/71, this note about timestamps isn't valid anymore (the clock is not monotonic anymore).

Update react-native-performance's README.md

---

packages/react-native-performance/package.json

#81 moved podspec out of the ios folder and thus removed it from the published artifact, breaking ios autolinking which it was supposed to fix. This PR adds it to the include list and back into the artifact.

Add missing podspec to published artifact

---

packages/react-native-performance/android/src/main/java/com/oblador/performance/PerformanceModule.java
packages/react-native-performance/android/src/main/java/com/oblador/performance/RNPerformance.java

Fix ConcurrentModificationException while calling emitBufferedMarks in Android
Currently, we are getting exception ConcurrentModificationException while calling emitBufferedMarks. The ArrayList is currently iterated and removed in the loop. To fix this iterator can be used, which checks if the element is present in the iterator before processing it. To solve the concurrency on multi threaded environment need to use some concurrent list. Here ConcurrentLinkedQueue can be used to solve the `ConcurrentModificationException` with the iterator.

Fix ConcurrentModificationException while calling emitBufferedMarks in Android

---

packages/react-native-performance/src/performance.ts
packages/react-native-performance/test/performance-now.spec.ts

For APERF-943 (which we're not doing but the proposed fix seems good regardless). Verified in a minimal repro that this works.

fix: Prevent infinite recursion if global.performance is exported ponyfill

---

examples/react-native-navigation/ios/Podfile.lock
examples/vanilla/ios/Podfile.lock
packages/react-native-performance/react-native-performance.podspec

I learned that this is actually not required, and will create issues with supporting multiple versions of `react-native`.

Use loose version of folly

---

examples/vanilla/App.tsx
examples/vanilla/ios/Example/AppDelegate.mm
packages/react-native-performance/ios/RNPerformanceManager.mm

First and subsequent launches of the iOS app will have a different order of content appear and script events. I think this is somehow incorrect, but since these are core events I can't really fix them in this library, so instead this PR changes the logic to wait for both to have been emitted.

Fix initial event emission on iOS and tracing in example app

---

examples/react-native-navigation/package.json
examples/vanilla/ios/Podfile.lock
examples/vanilla/package.json
examples/vanilla/tsconfig.json
examples/web/package.json
package.json
packages/isomorphic-performance/package.json
packages/react-native-performance/README.md
packages/react-native-performance/android/src/main/java/com/oblador/performance/PerformanceModule.java
packages/react-native-performance/android/src/main/java/com/oblador/performance/RNPerformance.java
packages/react-native-performance/android/src/main/java/com/oblador/performance/StartTimeProvider.java
packages/react-native-performance/ios/RNPerformance.h
packages/react-native-performance/ios/RNPerformanceEntry.h
packages/react-native-performance/package.json
yarn.lock

In React 0.68.3, the performance clock went back to monotonic (see https://github.com/facebook/react-native/blob/main/CHANGELOG.md#v0683).
This PR updates the react-native-performance package to use the same clock.

Switch back to monotonic clock & upgrade to RN 0.68.3

---

examples/vanilla/ios/Podfile.lock
packages/react-native-performance/ios/RNPerformanceManager.mm

As discussed in #68 the iOS prewarming of apps might caused distorted native launch measurements. We've had similar issues on android where fork time could be days in the past causing weird outliers in RUM that skew avg metrics (which is why I predominantly use median instead of average). 
This PR changes the iOS native launch metrics to be based on main() process only, thereby skipping any warmup steps done by the OS to load different system libraries etc. This will inevitably make this duration shorter for super-cold launches, but way less variance – in my testing repeat launches (aka not the first launch after install) give similar number to before. 
Curious to get feedback on this change @colinta @opayen @j-piasecki @mikeduminy

Ignore iOS prewarming

---

packages/isomorphic-performance/src/node.js

This PR fixes the Node.js wrapper in `isomorphic-performance` to work in Node.js 19+, which added brand checks on `performance` in https://github.com/nodejs/node/pull/44483.
Resolves https://github.com/oblador/react-native-performance/issues/100.

fix(node): bind `performance` to support node 19+

---

packages/react-native-performance/android/src/main/java/com/oblador/performance/PerformanceModule.java

This PR fixes Crash on Android when using this library #106 
To solve this problem, we need to check if ReactContext is initialized.
Ref: https://stackoverflow.com/questions/41120491/react-native-reactcontext-lifecycle-stuck-on-before-create

fix(android): crash when library try to access JSModule before it is initialized

---

examples/vanilla/ios/Example/AppDelegate.swift
packages/react-native-performance/ios/RNPerformanceEntry.h
packages/react-native-performance/ios/RNPerformanceManager.mm

The logger isn't easily accessible on bridgeless mode, but there is an alternative in the `ReactMarker::StartupLogger` singleton. The main downside with this one is that it doesn't have all the markers, nor does it update when app is reloaded. 
#111

Fix bridgeless mode on iOS
